### ISSUE TITLE
Where are the wiki page?

### ISSUE THREAD

**Issue by xchern** [awesomeWM/awesomeWM.github.io#3]
As the title. I cannot find them on the website. Deleted?

**Comment by xchern** [comment]
I finally see this [issue](https://github.com/awesomeWM/awesome-www/issues/7). So, no new wiki pages are yet established, right?

**Comment by psychon** [comment]
A "static backup" of the old ones is here: https://github.com/awesomeWM/awesome-www-backup-old/tree/gh-pages/wiki
It can be access online here: https://awesomewm.org/awesome-www-backup-old/wiki/
However, links are broken (why do these things have to use absolute URLs??), so you'll have to fix up links to other pages.

Our of curiosity: What are you looking for in the wiki? Put differently: Which content is the most valuable to you and needs to be saved?

**Comment by xchern** [comment]
Thanks, I'm just tring to vist with google cache.
Actually, I've just start to try awesomewm today, having seen some introduction from other sites which have hyperlinks to your wiki pages.
A good wiki can help newbies (like me) to get an global view and get involved easily, and can give the best solution to some common problem (this can prevent some dirty hack), which might not be so important for old users, I think.

**Comment by psychon** [comment]
Another option might be archive.org.

We are working on improving https://awesomewm.org/apidoc/ to the point that it contains all the stuff that the wiki had. For example: https://awesomewm.org/apidoc/documentation/05-awesomerc.md.html
