### ISSUE TITLE
Awesome logo copyright question

### ISSUE THREAD

**Issue by geripgeri** [awesomeWM/awesomeWM.github.io#6]
I would like to put a link to my personal webpage to my github config
repo. Can I use the official logo, can I modify it?
(https://s3.amazonaws.com/cloud.ohloh.net/attachments/6530/aw_64_shadow_med.png
or https://awesomewm.org/images/awesome-logo.svg )

**Comment by psychon** [comment]
I guess the GPL also applies, to the image doesn't it? I'm not sure what requirements follow from that. You may not remove the (non-existent) copyright line from the logo. ;-)
Anyway, fine with me (but I'm not the author of the logo).

**Comment by blueyed** [comment]
IIRC I have added the image to ohloh (https://s3.amazonaws.com/cloud.ohloh.net/attachments/6530/aw_64_shadow_med.png).

The awesome-logo.svg comes via https://github.com/awesomeWM/awesome-www/commit/8dec211.

IMHO you should just use it, if it is done with good intentions.

Thanks for asking, I think we can close this issue for now.

**Comment by geripgeri** [comment]
Thank you!
